---

- hosts: leaf:spine
  become: true
  ignore_errors: yes
  tasks:
    - shell: dpkg --list | grep kernel
      register: kernel_version

    - debug:
        var: kernel_version.stdout_lines


- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "frr_ospf_routes_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf:spine
  become: true
  tasks:
    - name: Take backup of /etc/frr/ospfd.conf
      copy:
        src: "{{ frr_ospf_conf_file }}"
        dest: "{{ frr_ospf_conf_file_bck }}"
        remote_src: true

    - name: Add ospf config in /etc/frr/ospfd.conf
      blockinfile:
        path: "{{ frr_ospf_conf_file }}"
        marker: ""
        block: |
          router ospf
          ospf router-id {{ ansible_ssh_host }}
          log-adjacency-changes
          redistribute connected
          network 10.0.3.0/24 area 0.0.0.0
          network 10.0.19.0/24 area 0.0.0.0

    - name: Restart frr
      service:
        name: frr
        state: restarted

    - name: Wait few seconds for ospf to establish connection
      pause:
        seconds: 35

    - file:
        path: "{{ ospf_log_dir }}"
        state: directory

    - name: Verify ospf routes
      test_ospf_basic:
        switch_name: "{{ inventory_hostname }}"
        spine_list: "{{ groups['spine'] }}"
        spine_ips: "{{ groups['spine'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
        leaf_ips: "{{ groups['leaf'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
        package_name: "frr"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ospf_log_dir }}"
        check_route: True
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1

    - include: ../../playbooks/get_goes_version_and_tags.yml


- include: frr_ospf_routes_reset.yml
  when: reset_config


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result

    - name: Print test case result
      debug:
        msg: "Test case result: {{ result.result_status }}"

    - name: Print failure summary
      debug:
        msg: "Failure summary: {{ result.result_detail }}"

    - lineinfile:
        path: "{{ regression_summary_report }}"
        line: "{{ hash_name }}: {{ result.result_status }}"


- hosts: leaf:spine
  become: true
  tasks:
    - include: ../../playbooks/get_goes_status.yml
