---

- hosts: leaf:spine
  become: true
  tasks:
    - name: Restore backup of /etc/frr/ospfd.conf
      copy:
        src: "{{ frr_ospf_conf_file_bck }}"
        dest: "{{ frr_ospf_conf_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ frr_ospf_conf_file_bck }}"
        state: absent

    - name: Restart frr
      service:
        name: frr
        state: restarted
