---

- hosts: leaf[0]
  become: true
  tasks:
    - name: Stop iperf server instances
      command: "pkill iperf"

    - shell: "rm ~/iperf-parallel-servers.sh"


- hosts: leaf:spine
  become: true
  tasks:
    - name: Remove config file
      file:
        path: "{{ gobgp_bgp_conf_file }}"
        state: absent

    - name: Restore backup of /etc/quagga/zebra.conf
      copy:
        src: "{{ quagga_zebra_conf_file_bck }}"
        dest: "{{ quagga_zebra_conf_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ quagga_zebra_conf_file_bck }}"
        state: absent

    - name: Delete dummy interface
      command: "ip link del dummy0 type dummy"

    - name: Restart quagga
      service:
        name: quagga
        state: restarted
