---

# Uninstall packages stack
- include: playbooks/installation/uninstall_packages.yml


# Reset the setup
- include: playbooks/master_reset_invaders.yml


# Install gobgp
- include: playbooks/installation/gobgp_install.yml


# Run all gobgp bgp test cases
- include: playbooks/bgp/gobgp_bgp_peering_ebgp.yml

- include: playbooks/bgp/gobgp_bgp_peering_ebgp_loopback.yml

- include: playbooks/bgp/gobgp_bgp_peering_ebgp_route_advertise.yml

- include: playbooks/bgp/gobgp_bgp_peering_ibgp.yml

- include: playbooks/bgp/gobgp_bgp_peering_ibgp_loopback.yml

- include: playbooks/bgp/gobgp_bgp_peering_ibgp_route_advertise.yml

- include: playbooks/bgp/gobgp_bgp_peering_administrative_distance.yml

- include: playbooks/bgp/gobgp_bgp_peering_authentication.yml

- include: playbooks/bgp/gobgp_bgp_peering_local_preference.yml

- include: playbooks/bgp/gobgp_bgp_peering_as_path.yml

- include: playbooks/bgp/gobgp_bgp_peering_route_reflector.yml

#- include: playbooks/bgp/gobgp_bgp_peering_redundancy.yml

- include: playbooks/bgp/gobgp_bgp_peering_consistency.yml

- include: playbooks/bgp/gobgp_bgp_peering_if_down.yml

- include: playbooks/bgp/gobgp_bgp_peering_loop_prevention.yml

- include: playbooks/bgp/gobgp_bgp_state_propagation.yml

- include: playbooks/bgp/gobgp_bgp_convergence.yml
