---

- hosts: leaf:spine
  become: true
  ignore_errors: yes
  tasks:
    - shell: dpkg --list | grep kernel
      register: kernel_version

    - debug:
        var: kernel_version.stdout_lines


- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "vlan_configuration_dhcp_vlan_interfaces_and_physical_interfaces_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf[0]
  become: true
  tasks:
    - name: Install dhcp
      apt:
        name: isc-dhcp-server
        state: present

    - name: Copy isc-dhcp-server file for vlan to /etc/default/isc-dhcp-server
      copy:
        src: "../../files/{{inventory_hostname}}/vlan_isc_dhcp_server"
        dest: "/etc/default/isc-dhcp-server"

    - name: Copy dhcpd config file to /etc/dhcp/dhcpd.conf
      copy:
        src: "../../files/{{inventory_hostname}}/vlan_dhcpd.conf"
        dest: "/etc/dhcp/dhcpd.conf"


- hosts: leaf[0]:spine[0]
  become: yes
  tasks:
    - file:
        path: "{{ vlan_log_dir }}"
        state: directory

    - name: Take backup of /etc/network/interfaces
      copy:
        src: "{{ network_interfaces_file }}"
        dest: "{{ network_interfaces_file_bck }}"
        remote_src: true

    - name: Copy ipv4 configuration interfaces network file
      copy:
        src: "../../files/{{inventory_hostname}}/vlan_dhcp_interfaces"
        dest: "{{ network_interfaces_file }}"

    - name: Restart goes
      command: goes restart    

    - name: Test vlan configuration dhcp vlan interfaces and physical interfaces
      test_dhcp_vlan_configuration:
        switch_name: "{{ inventory_hostname }}"
        leaf_switch: "{{ groups['leaf'][0] }}"
        eth: "5"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ vlan_log_dir }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1

    - name: Restore backup of /etc/network/interfaces
      copy:
        src: "{{ network_interfaces_file_bck }}"
        dest: "{{ network_interfaces_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ network_interfaces_file_bck }}"
        state: absent


- hosts: leaf[0]
  become: true
  tasks:
    - name: Uninstall dhcp
      apt:
        name: isc-dhcp-server
        state: absent


- hosts: leaf:spine
  become: yes
  tasks:
    - include: ../../playbooks/get_goes_version_and_tags.yml


- include: ../../playbooks/master_reset_invaders.yml
  when: reset_config


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result

    - name: Print test case result
      debug:
        msg: "Test case result: {{ result.result_status }}"

    - name: Print failure summary
      debug:
        msg: "Failure summary: {{ result.result_detail }}"

    - lineinfile:
        path: "{{ regression_summary_report }}"
        line: "{{ hash_name }}: {{ result.result_status }}"


- hosts: leaf:spine
  become: true
  tasks:
    - include: ../../playbooks/get_goes_status.yml
