---

- hosts: leaf:spine
  become: true
  ignore_errors: yes
  tasks:
    - name: Delete any existing namespaces
      command: ip -all netns del

    - name: Stop any existing iperf sessions
      command: pkill iperf

    - name: Stop and remove any existing docker containers
      shell: "{{ item }}"
      with_items:
      - "docker stop $(docker ps -a -q)"
      - "docker rm $(docker ps -a -q)"

    - name: Copy default network interfaces file
      template:
        src: "../files/{{inventory_hostname}}/network_interfaces_master"
        dest: "{{ network_interfaces_file }}"

    - name: Execute commands
      command: "{{ item }}"
      with_items:
      - 'goes stop'
      - 'rmmod platina-mk1'
      - 'modprobe platina-mk1'
      - 'ifdown -a --allow vnet'
      - 'ifup -a'
      - 'goes start'

    - name: Wait few seconds for GOES to come up
      pause:
        seconds: 15

    - include: get_goes_status.yml

    - name: Verify link status b/w invaders
      verify_links:
        switch_name: "{{ inventory_hostname }}"
        leaf_list: "{{ groups['leaf'] }}"
        eth_list: "1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31"
        platina_redis_channel: "{{ platina_redis_channel }}"
      register: module_out

    - name: Print Link Status
      debug:
        var: module_out

