---

- hosts: leaf:spine
  become: true
  ignore_errors: yes
  tasks:
    - name: Delete any existing namespaces
      command: ip -all netns del

    - name: Stop any existing iperf sessions
      command: pkill iperf

    - name: Copy default network interfaces file
      template:
        src: "../../files/{{inventory_hostname}}/network_interfaces_master"
        dest: "{{ network_interfaces_file }}"

    - name: Execute commands
      command: "{{ item }}"
      with_items:
      - 'goes stop'
      - 'rmmod platina-mk1'
      - 'modprobe platina-mk1'
      - 'ifdown -a --allow vnet'
      - 'ifup -a'
      - 'goes start'

    - name: Wait few seconds for GOES to come up
      pause:
        seconds: 5

